### ISSUE TITLE
Remove `-nsis` flag for `windows/386`

### ISSUE THREAD

**Issue by kkrypt0nn** [dAppServer/wails-build-action#13]
Since Wails does not officially support `windows/386` and cannot built an NSIS installer for it, it would be nice to remove the `-nsis` flag from the build command for that specific architecture and just publish the generated executable to the release assets.

Without the `-nsis` flag it successfully builds an executable - with the `-nsis` flag it fails.

Alternatively for more customization it could be an option that can set specified in the workflow `yml` file.

See https://github.com/wailsapp/wails/issues/2607 for some context

**Comment by Snider** [comment]
You can pass nsis: 'false' now with v2.1
```
  windows:
    runs-on: windows-2022
    steps:
      - uses: dAppServer/wails-build-action@v2.1
        with:
          build-platform: windows/amd64
          wails-build-webview2: "embed"
          wails-version: v2.3.1
          go-version: ^1.18
          nsis: "false"
          
 ```
