### ISSUE TITLE
Action hangs with nektos/act while installing on ubuntu

### ISSUE THREAD

**Issue by ncpleslie** [dAppServer/wails-build-action#15]
Action hangs while installing dependencies when using [nektos/act](https://github.com/nektos/act) to test the action locally.

My current usage (Most of the action has been removed for brevity:
```YAML
...
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
            { name: wailsTest, platform: linux/amd64, os: ubuntu-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      # steps removed for brevity
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.21"
          node-version: 18
...
```

Output from terminal:
```
   ubuntu-mono wayland-protocols xdg-dbus-proxy xdg-desktop-portal
   xdg-desktop-portal-gtk xkb-data
 0 upgraded, 238 newly installed, 0 to remove and 30 not upgraded.
 Need to get 145 MB of archives.
 After this operation, 578 MB of additional disk space will be used.
```

According to [this issue](https://github.com/nektos/act/issues/1190) on the Act repo, "It's hanging on confirmation to install packages [Y/n] prompt in which case apt should be run with -y flag"

Fix:
Update `line 133` of action.yml from:

```
run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
```
to

```
run: sudo apt-get update && sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
```

I can confirm this has fixed my issue on [my fork](https://github.com/ncpleslie/wails-build-action)
I can put a PR up with the fix, if requested. 

Thanks.
