### ISSUE TITLE
Action fails every time on "Run dAppServer/wails-build-action@v2" step

### ISSUE THREAD

**Issue by Narixius** [dAppServer/wails-build-action#5]
Hi, thank you for this project
I am using this action on a wails repo with the following config
```yml
name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [{ name: AppName, platform: linux/amd64, os: ubuntu-latest }, { name: AppName, platform: windows/amd64, os: windows-latest }, { name: AppName, platform: darwin/universal, os: macos-latest }]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
```
But the action fails with the following output every time on the "Run dAppServer/wails-build-action@v2" step.
```
Run dAppServer/wails-build-action@v2
Run actions/setup-go@v2
Setup go stable version spec 1.17
Found in cache @ /opt/hostedtoolcache/go/1.17.13/x64
Added go to the path
Successfully setup go version 1.17
go version go1.17.13 linux/amd64

go env
Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/16.17.1/x64
Run go install github.com/wailsapp/wails/v2/cmd/wails@latest
go: downloading github.com/wailsapp/wails v1.16.9
go: downloading github.com/wailsapp/wails/v2 v2.1.0
go: downloading github.com/leaanthony/clir v1.0.4
...
[ ... several packages are downloading here ....]
...
go: downloading github.com/dlclark/regexp2 v1.4.0
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading gopkg.in/warnings.v0 v0.1.2
go: downloading github.com/gorilla/css v1.0.0
Error: ../../../go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/pkg/templates/templates.go:28:12: pattern all:ides/*: no matching files found
Error: Process completed with exit code 1.
```
I guess it is not related to this repo because this error occurs on downloading the package on the OS.
But do you have any idea about this issue?
Let me know if you need more information about the repo.
Thanks.
